### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ThePowerOfSwift** [pronebird/CollectionViewCheckbox#2]
Merge current "master" to "Swift-3.0" branch, and make it compilable with Xcode 8.0.

Swift 3 Support.

**Comment by pronebird** [comment]
Your PR has been merged to master. It works fine with Xcode 8. Is there anything else to be done?

**Comment by ThePowerOfSwift** [comment]
@pronebird , No, everything is OK 👍  Thank You :)

**Comment by pronebird** [comment]
@mihailsalari great! Thanks!
